version: "3.2"
services:
  db_mysql:
    image: mariadb:10.3.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    volumes:
      - type: volume
        target: /var/lib/mysql
        source: user_db
  clip_management:
    image: zigakern/user_management:v0.1.0
    ports:
      - 8082:8082
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:mysql://db_mysql:3306/users
      - KUMULUZEE_SERVER_BASE-URL=http://192.168.99.100:8082
    depends_on:
      - db_mysql

volumes:
    user_db: