apiVersion: v1
kind: Service
metadata:
    name: user-management
    labels:
        app: user-management
spec:
    ports:
        - port: 8082
    selector:
        app: user-management
        tier: app
    type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
    name: user-management
    labels: 
      app: user-management
spec:
    minReadySeconds: 0
    replicas: 1
    selector:
        matchLabels:
            app: user-management
            tier: app
    template: 
        metadata:
            labels:
                app: user-management
                tier: app
        spec:
            containers:
                - name: app-clip
                  image: zigakern/user_management:v0.1.0
                  env:
                    - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
                      value: jdbc:mysql://users-mysql:3307/users
                    - name: KUMULUZEE_CONFIG_ETCD_HOSTS
                      value: http://etcd:2379
                    - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
                      value: http://etcd:2379
                    - name: KUMULUZEE_SERVER_BASE-URL
                      value: http://user-management:8082
                  ports:
                    - containerPort: 8082
                      name: app
                      protocol: TCP
                  livenessProbe:
                        httpGet:
                          path: /health
                          port: 8082
                        initialDelaySeconds: 60
                        periodSeconds: 5