apiVersion: v1
kind: Service
metadata:
    name: clip-management
    labels:
        app: clip-management
spec:
    ports:
        - port: 8081
    selector:
        app: clip-management
        tier: app
    type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
    name: clip-management
    labels: 
      app: clip-management
spec:
    minReadySeconds: 0
    replicas: 1
    selector:
        matchLabels:
            app: clip-management
            tier: app
    template: 
        metadata:
            labels:
                app: clip-management
                tier: app
        spec:
            containers:
                - name: app-clip
                  image: zigakern/clip_management:v0.1.5
                  env:
                    - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
                      value: jdbc:mysql://clip-mysql:3306/clips
                    - name: KUMULUZEE_CONFIG_ETCD_HOSTS
                      value: http://etcd:2379
                    - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
                      value: http://etcd:2379
                    - name: KUMULUZEE_SERVER_BASE-URL
                      value: http://clip-management:8081
                  ports:
                    - containerPort: 8081
                      name: app
                      protocol: TCP
                  livenessProbe:
                        httpGet:
                          path: /health
                          port: 8081
                        initialDelaySeconds: 60
                        periodSeconds: 5