kumuluzee:
  name: user_management
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/UsersDB
      connection-url: jdbc:mysql://192.168.99.100:3306/users
      username: root
      password: root
      max-pool-size: 20
  config:
      etcd:
        hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
  logs:
      config-file:
        '<?xml version="1.0" encoding="UTF-8"?>
         <Configuration name="clip-logging">
             <Appenders>
                 <Console name="console" target="SYSTEM_OUT">
                     <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                 </Console>
                 <Socket name="logstash" host="a74a2a0e-e621-4208-84ae-7662068886fb-ls.logit.io" port="22776" protocol="tcp">
                     <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                 </Socket>
             </Appenders>
             <Loggers>
                 <!-- Default logger -->
                 <Root level="all">
                     <AppenderRef ref="console" level="info"/>
                     <AppenderRef ref="logstash" level="info"/>
                 </Root>
             </Loggers>
         </Configuration>'
  health:
      logs:
            enabled: true
            level: FINE
            period-s: 60
      checks:
        data-source-health-check:
          jndi-name: jdbc/UsersDB
        http-health-check:
                connection-url: http://localhost:8082/v1/users/healthResponseCheck
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: usersEndpoint
        url-pattern: /v1/users/*
